# Generated by Django 4.1.2 on 2022-10-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('slideshow', models.BooleanField(default=False)),
            ],
        ),
    ]
