# Generated by Django 4.1.2 on 2022-10-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='positions',
            name='position',
            field=models.CharField(default='MEMBER', max_length=25, unique=True),
        ),
    ]
