# Generated by Django 4.1.2 on 2022-10-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fryums',
            name='importance',
            field=models.IntegerField(default=0),
        ),
    ]
