# Generated by Django 4.1.2 on 2022-10-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journalclub', '0002_fryums_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journalclub.event'),
            preserve_default=False,
        ),
    ]
